[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"
authors = ["Oskar Lindén <cephlot@protonmail.com>"]
repository = "https://github.com/cephlot/raytracer"

[dependencies]

[lib]
name = "libray"
path = "src/lib.rs"
